Implement Wellington layout
Voog/design-wellington pull request #1
Opened 2023-09-21 12:15 UTC by PeeterPaal

2023-09-25 11:08 UTC, tanelj requested changes
Nice work!

Here is first feedback mostly about Liquid tweaks.

2023-09-25 11:08 UTC, tanelj commented on components/html-head.tpl
> +<link rel="stylesheet" href="{{ site.static_asset_host }}/libs/edicy-search/latest/edicy-search.css">
```suggestion
{% if site.search.enabled -%}
  {% stylesheet_link "libs/edicy-search/latest/edicy-search.css" static_host="true" %}
{%- endif %}
```

2023-09-25 11:08 UTC, tanelj commented on components/html-head.tpl
> +{% endif %}
Let's use [stylesheet_link](https://www.voog.com/developers/markup/tags/stylesheet-link) tag.
```suggestion
{% if editmode -%}
  {% stylesheet_link "libs/edicy-tools/latest/edicy-tools.css" static_host="true" %}
{%- endif %}
```

2023-09-25 11:08 UTC, tanelj commented on components/search.tpl
> +        <input id="onpage_search" class="search-input js-search-input js-input-dynamic" type="text" name="" placeholder="{{  'search' | lc }}">
Let's add [escape_once](https://www.voog.com/developers/markup/basics/filters#escape_once) filter to ensure that external string doesn't brake html.
```suggestion
        <input id="onpage_search" class="search-input js-search-input js-input-dynamic" type="text" name="" placeholder="{{ "search" | lc | escape_once }}">
```

2023-09-25 11:08 UTC, tanelj commented on components/search.tpl
> +        <input class="search-submit js-search-submit" type="submit" value="Search" name="">
```suggestion
        <input class="search-submit js-search-submit" type="submit" value="{{ "search" | lc | escape_once }}" name="">
```

2023-09-25 11:08 UTC, tanelj commented on components/template-meta.tpl
> +<meta property="og:url" content="{{ site.url }}{{ og_obj.url | remove_first:"/" }}">
```suggestion
<meta property="og:url" content="{{ site.url }}{{ og_obj.url | remove_first: "/" }}">
```

2023-09-25 11:08 UTC, tanelj commented on components/template-meta.tpl
> +<meta property="og:site_name" content="{{ page.site_title | escape }}">
[escape_once](https://www.voog.com/developers/markup/basics/filters#escape_once)` should be better.
```suggestion
<meta property="og:site_name" content="{{ page.site_title | escape_once }}">
```

2023-09-25 11:08 UTC, tanelj commented on components/javascripts.tpl
> +{% if site.search.enabled %}
```suggestion
{% if site.search.enabled -%}
```

2023-09-25 11:08 UTC, tanelj commented on components/javascripts.tpl
> +{% endif %}
```suggestion
{%- endif %}
```

2023-09-25 11:08 UTC, tanelj commented on components/javascripts.tpl
> +  <script>site.bindSiteSearch($('.js-search-form').get(0), '{{ page.language_code }}', '{{ 'search_noresults' | lc | escape }}');</script>
```suggestion
  <script>site.bindSiteSearch($('.js-search-form').get(0), '{{ page.language_code }}', {{ 'search_noresults' | lc | json }});</script>
```

2023-09-25 11:08 UTC, tanelj commented on components/javascripts.tpl
> +{% comment %}GOOGLE ANALYTICS INITIATION{% endcomment %}
```suggestion
{% comment %}SITE ANALYTICS INITIATION{% endcomment %}
```

2023-09-25 11:08 UTC, tanelj commented on components/menu-main.tpl
> +            <li>{% menuadd parent=item %}</li>
Second level "Add subpage"  button is not shown where the parent page is active, but has no children. It must be always shown for non root page.

2023-09-25 11:08 UTC, tanelj commented on components/menu-main.tpl
> +  <ul class="menu">
White spaces removal can be improved.

2023-09-25 11:08 UTC, tanelj commented on components/menu-lang.tpl
> +  {% for language in site.languages %}
```suggestion
  {% for language in site.languages -%}
```

2023-09-25 11:08 UTC, tanelj commented on components/menu-lang.tpl
> +  {% endfor %}
```suggestion
  {%- endfor %}
```

2023-09-25 11:08 UTC, tanelj commented on components/menu-lang.tpl
> +  {% if editmode %}
```suggestion
  {% if editmode -%}
```

2023-09-25 11:08 UTC, tanelj commented on components/menu-lang.tpl
> +  {% endif %}
```suggestion
  {%- endif %}
```

2023-09-25 11:08 UTC, tanelj commented on components/javascripts.tpl
> +<script src="{{ javascripts_path }}/application.min.js?v={{ template_settings.version }}"></script>
```suggestion
<script src="{{ javascripts_path }}/application.min.js?v={{ template_settings.version }}"></script>
{% if editmode -%}
  <script src="{{ javascripts_path }}/editmode.min.js?v={{ template_settings.version }}"></script>
{%- endif %}
```

2023-09-25 11:08 UTC, tanelj commented on sources/stylesheets/_content-formatted.scss
> +}
Please add image/map/video container related base styles: https://www.voog.com/developers/markup/basics/smarter-media

Please add form area basic CSS boilerplate (small/medium/large).

2023-09-26 05:32 UTC, t-p-developer commented on javascripts/editmode.js
> +              ;
nit! Let's put `;` in the above line. Please check the rest of the file also, there is the same inconsistency.

2023-09-26 05:32 UTC, t-p-developer commented on javascripts/editmode.js
> +                  }
nit! Can we extract this logic? At the moment, it seems like a `callback-hell`...

2023-09-26 05:32 UTC, t-p-developer commented on javascripts/editmode.js
> +            });        } else {
nit! Formatting.

2023-09-26 06:28 UTC, PeeterPaal commented on javascripts/editmode.js
> +                  }
This logic is copied over from other standard layouts. I would keep it largely unchanged.

2023-09-26 06:36 UTC, PeeterPaal commented on javascripts/editmode.js
> +                  }
Took a closer look – this part seems to be a bit unnecessary, as crop toggles are not present in every design. This logic also seems tied to product & article images, which went unnoticed.

I'd keep other general scripts (bgpicker, custom data etc.), as these are perhaps more widely used.

2023-09-26 08:38 UTC, t-p-developer commented on .prettierrc
> +{
🏅

2023-09-26 08:39 UTC, t-p-developer commented on .prettierrc
> +}
🏅

2023-11-09 14:48 UTC, tanelj approved these changes
Nice!

2023-11-29 07:19 UTC, tanelj requested changes
Nice work! Here are some feedback.

2023-11-29 07:19 UTC, tanelj commented on components/bg-picker-scripts.tpl
> +      var $picker = $(pickerArea).find('.bg-picker');
Its nice to guard against missing `bg-picker` element.

2023-11-29 07:19 UTC, tanelj commented on components/template-styles.tpl
> +    background-image: url("{{ body_bg_image }}");
NB! Do not render when `body_bg_image` is empty (renders current page html when url is missing).

```suggestion
    {% if  body_bg_image != blank%}background-image: url("{{ body_bg_image }}");{% endif %}

2023-11-29 07:19 UTC, tanelj commented on components/header.tpl
> +    {% if site.search.enabled %}
```suggestion
    {%- if site.search.enabled %}
```

2023-11-29 07:19 UTC, tanelj commented on components/header.tpl
> +    {% endif %}
```suggestion
    {%- endif %}
```

2023-11-29 07:19 UTC, tanelj commented on components/javascripts.tpl
> +{% if editmode %}
```suggestion
{%- if editmode %}
```

2023-11-29 07:19 UTC, tanelj commented on components/javascripts.tpl
> +{% endif %}
```suggestion
{%- endif %}
```

2023-11-29 07:19 UTC, tanelj commented on components/template-meta.tpl
> +  {%- if og_image.url -%}<meta property="og:image" content="{{ og_image.url | replace_first: "http:", "" | replace_first: "https:", "" | prepend: "https:" }}">{%- endif -%}
The `og_image` is always Image object (is not coming from object data attribute) so:
```suggestion
  {{% if og_image.url %}<meta property="og:image" content="{{ og_image.url }}">{% endif %}
```

2023-11-29 07:19 UTC, tanelj commented on layouts/front_page.tpl
> +    {% if editmode %}
```suggestion
    {%- if editmode %}
```

2023-11-29 07:19 UTC, tanelj commented on layouts/front_page.tpl
> +    {% endif %}
```suggestion
    {% endif -%}
```

2023-11-29 07:19 UTC, tanelj commented on manifest.json
> +      "title": "Front page"
Maybe we should name it common page?

```suggestion
      "file": "layouts/common_page.tpl",
      "layout_name": "page_default",
      "title": "Common page"
```

2023-11-29 14:38 UTC, tanelj approved these changes
Nice work!

2023-11-29 14:38 UTC, merged